### ISSUE TITLE
关于在线编辑器文档

### ISSUE THREAD

**Issue by yelloxing** [hai2007/SweetHome#2]
当我们打开[在线编辑器](https://hai2007.gitee.io/sweethome/#/editor)的时候，默认打开的是初始界面，是不是可以在这个界面添加文档引导，帮助第一次发现的人学会如何使用？

引导的文档在readme.md中，应该做到可以直接定位具体位置。

**Comment by yelloxing** [comment]
推荐添加这个地址：[文档地址](https://github.com/hai2007/SweetHome#在线代码演示)，在页面中添加。

**Comment by hai2007** [comment]
已经优化
