### ISSUE TITLE
关于开发web端的简化版本Excel项目：Open Web Excel

### ISSUE THREAD

**Issue by yelloxing** [hai2007/SweetHome#4]
多人协调编辑excel的时候，代码合并不是很方便，对于网上的已经有的，不够灵活而且不安全，因此可以开发一个普通的web版本excel，数据和别的安全策略由使用者自己搭建，这里主要维护产品本身。

**Comment by hai2007** [comment]
https://github.com/hai2007/Open-Web-Excel
